import type { Shipment } from "../types/types";

export const shipmentsSampleData: Shipment[] = [
  {
    _id: "1",
    productName: "Paracetamol 500mg",
    quantity: 5,
    status: "PENDING",
    createdAt: new Date("2022-01-01").toISOString(),
    updatedAt: new Date("2022-01-01").toISOString(),
    deleveryDate: new Date("2022-01-01").toISOString(),
    userId: "1",
  },
  {
    _id: "2",
    productName: "Amoxicillin 250mg",
    quantity: 10,
    status: "IN_TRANSIT",
    createdAt: new Date("2022-02-01").toISOString(),
    updatedAt: new Date("2022-02-01").toISOString(),
    deleveryDate: new Date("2022-02-05").toISOString(),
    userId: "2",
  },
  {
    _id: "3",
    productName: "Ibuprofen 200mg",
    quantity: 3,
    status: "DELIVERED",
    createdAt: new Date("2022-03-01").toISOString(),
    updatedAt: new Date("2022-03-02").toISOString(),
    deleveryDate: new Date("2022-03-03").toISOString(),
    userId: "3",
  },
  {
    _id: "4",
    productName: "Cetirizine 10mg",
    quantity: 7,
    status: "PENDING",
    createdAt: new Date("2022-04-01").toISOString(),
    updatedAt: new Date("2022-04-02").toISOString(),
    deleveryDate: new Date("2022-04-05").toISOString(),
    userId: "4",
  },
  {
    _id: "5",
    productName: "Metformin 500mg",
    quantity: 12,
    status: "IN_TRANSIT",
    createdAt: new Date("2022-05-01").toISOString(),
    updatedAt: new Date("2022-05-02").toISOString(),
    deleveryDate: new Date("2022-05-07").toISOString(),
    userId: "5",
  },
  {
    _id: "6",
    productName: "Lisinopril 10mg",
    quantity: 15,
    status: "DELIVERED",
    createdAt: new Date("2022-06-01").toISOString(),
    updatedAt: new Date("2022-06-02").toISOString(),
    deleveryDate: new Date("2022-06-04").toISOString(),
    userId: "6",
  },
  {
    _id: "7",
    productName: "Salbutamol Inhaler",
    quantity: 9,
    status: "PENDING",
    createdAt: new Date("2022-07-01").toISOString(),
    updatedAt: new Date("2022-07-02").toISOString(),
    deleveryDate: new Date("2022-07-05").toISOString(),
    userId: "7",
  },
];
